branches:
  only:
    - master
language: java
matrix:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
    - os: osx
      osx_image: xcode10.1
cache:
  directories:
  - "$HOME/.m2"
install:
  - echo "<settings><profiles><profile><repositories><repository><snapshots><enabled>false</enabled></snapshots><id>central</id><name>bintray</name><url>https://jcenter.bintray.com</url></repository></repositories><pluginRepositories><pluginRepository><snapshots><enabled>false</enabled></snapshots><id>central</id><name>bintray-plugins</name><url>https://jcenter.bintray.com</url></pluginRepository></pluginRepositories><id>bintray</id></profile></profiles><activeProfiles><activeProfile>bintray</activeProfile></activeProfiles></settings>" > $HOME/.m2/settings.xml
script:
  - mvn clean install --batch-mode
